title: Optimizacion Lineal
author: Esnil Guevara
email: esnilg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este sitio esta destinado al planteamiento y resolucion de problemas de programacion lineal.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
